### PR TITLE
This is older, however this is the last working version of vircadia-builder

### PR DESCRIPTION
**Pull request by digisomni**

### CODE REVIEW

**Comment by digisomni** [comment]
My only actual change is probably 'cmake3'.

**Comment by JulianGro** [comment]
What do you mean "this is the last working version of vircadia-builder"?

**Comment by digisomni** [comment]
Sorry, to be specific this is for Amazon Linux 2.

**Comment by daleglass** [comment]
Ok, this is obsolete at this point, so I'm closing it. Thanks for the help, though!

**Pull request closed without merging**
